apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: squid-java-springboot 
  janus-idp.io/tekton: squid-java-springboot
  backstage.io/kubernetes-id: squid-java-springboot
  backstage.io/kubernetes-namespace: rhtap-test-organization-jk 
  app.kubernetes.io/part-of: squid-java-springboot
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  